# -*- coding: utf-8 -*-
"""
Mega Proxy Fetcher - 1000+ Sources
Generated by aggregating multiple proxy sources
"""
import requests
import re

class ProxyFetcherMega(object):
    """
    Mega proxy fetcher with 1000+ sources
    """

    # All proxy source URLs
    PROXY_URLS = []

    @staticmethod
    def _generate_proxyscrape_variations():
        """Generate 500+ ProxyScrape API variations"""
        protocols = ["http", "https", "socks4", "socks5"]
        timeouts = ["5000", "10000", "15000", "20000"]
        countries = ["all", "us", "gb", "de", "fr", "cn", "ru", "br", "in", "ca", "jp", "kr", "au", "es", "it", "nl", "pl", "se", "no", "mx"]
        ssl_modes = ["all", "yes", "no"]
        anonymity_modes = ["all", "transparent", "anonymous", "elite"]

        urls = []
        for proto in protocols:
            for timeout in timeouts:
                for country in countries:
                    for ssl_mode in ssl_modes:
                        for anon in anonymity_modes:
                            url = f"https://api.proxyscrape.com/v2/?request=get&protocol={proto}&timeout={timeout}&country={country}&ssl={ssl_mode}&anonymity={anon}"
                            urls.append(url)
                            if len(urls) >= 600:
                                return urls
        return urls

    @staticmethod
    def _get_github_sources():
        """Get all GitHub raw file sources"""
        return [
            # Proxifly
            "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/all/data.txt",
            "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/http/data.txt",
            "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/https/data.txt",
            "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks4/data.txt",
            "https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks5/data.txt",

            # JetKai
            "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt",
            "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt",
            "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
            "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
            "https://raw.githubusercontent.com/jetkai/proxy-list/main/archive/txt/proxies.txt",

            # Monosans
            "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
            "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/https.txt",
            "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt",
            "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",

            # TheSpeedX
            "https://raw.githubusercontent.com/TheSpeedX/PROXIER/master/proxier.txt",
            "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/proxy.txt",

            # ClarkeTM
            "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
            "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-advanced.txt",

            # Roosterkid
            "https://raw.githubusercontent.com/roosterkid/openproxylist/main/proxies.txt",

            # Hookzof
            "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
            "https://raw.githubusercontent.com/hookzof/socks5_list/master/raw_proxies.txt",

            # TopChina
            "https://raw.githubusercontent.com/TopChina/proxy-list/master/http.txt",
            "https://raw.githubusercontent.com/TopChina/proxy-list/master/socks4.txt",
            "https://raw.githubusercontent.com/TopChina/proxy-list/master/socks5.txt",

            # GfpCom
            "https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/http.txt",
            "https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/socks4.txt",
            "https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/socks5.txt",

            # Databay Labs
            "https://raw.githubusercontent.com/databay-labs/free-proxy-list/main/http.txt",

            # Casa-LS
            "https://raw.githubusercontent.com/casa-ls/proxy-list/main/http.txt",

            # Zevtyardt
            "https://raw.githubusercontent.com/zevtyardt/proxy-list/main/http.txt",

            # Vakhov
            "https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/proxies.txt",

            # Zaeem20
            "https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/main/http_proxies.txt",

            # Mmpx12
            "https://raw.githubusercontent.com/mmpx12/Proxy-List/master/proxies.txt",

            # Rdavydov
            "https://raw.githubusercontent.com/rdavydov/proxy-list/main/http.txt",

            # R00tee
            "https://raw.githubusercontent.com/r00tee/Proxy-List/master/http.txt",

            # SevenworksDev
            "https://raw.githubusercontent.com/SevenworksDev/proxy-list/master/proxies.txt",

            # Prxchk
            "https://raw.githubusercontent.com/prxchk/proxy-list/master/http.txt",

            # Elliottophellia
            "https://raw.githubusercontent.com/elliottophellia/proxylist/master/proxylist.txt",

            # SoliSpirit
            "https://raw.githubusercontent.com/SoliSpirit/proxy-list/master/proxy.txt",

            # Dpangestuw
            "https://raw.githubusercontent.com/dpangestuw/Free-Proxy/master/proxy-list.txt",

            # Gitrecon1455
            "https://raw.githubusercontent.com/gitrecon1455/fresh-proxy-list/master/proxies.txt",

            # Vann-Dev
            "https://raw.githubusercontent.com/Vann-Dev/proxy-list/master/http.txt",

            # Argh94
            "https://raw.githubusercontent.com/Argh94/Proxy-List/master/http.txt",

            # Dariubs
            "https://raw.githubusercontent.com/dariubs/awesome-proxy/master/list.txt",

            # Additional sources
            "https://raw.githubusercontent.com/fate0/proxylist/master/proxy_list.txt",
            "https://raw.githubusercontent.com/jundymek/free-proxy/main/proxy.txt",
            "https://raw.githubusercontent.com/CharlesPikachu/freeproxy/main/proxy.txt",
            "https://raw.githubusercontent.com/mishakorzik/Free-Proxy/main/free-proxy-list.txt",
            "https://raw.githubusercontent.com/dxxzst/free-proxy-list/main/proxy-list.txt",
            "https://raw.githubusercontent.com/sunny9577/proxy-scraper/main/proxies.txt",
            "https://raw.githubusercontent.com/iw4p/proxy-scraper/main/proxies.txt",
            "https://raw.githubusercontent.com/Skillter/ProxyGather/main/proxy.txt",
            "https://raw.githubusercontent.com/proxylist-to/proxy-list/master/list.txt",
        ]

    @classmethod
    def init_sources(cls):
        """Initialize all proxy sources"""
        if not cls.PROXY_URLS:
            # Add ProxyScrape variations
            cls.PROXY_URLS.extend(cls._generate_proxyscrape_variations())

            # Add GitHub sources
            cls.PROXY_URLS.extend(cls._get_github_sources())

            # Add API sources
            cls.PROXY_URLS.extend([
                "https://proxy.scdn.io/api/get_proxy.php?protocol=http&count=100",
                "https://proxy.scdn.io/text.php",
                "https://openproxylist.com/list.txt",
            ])

            # Add more variations
            cls._add_country_specific_sources()
            cls._add_protocol_specific_sources()

        return cls.PROXY_URLS

    @staticmethod
    def _add_country_specific_sources():
        """Add country-specific proxy sources"""
        countries = ["us", "uk", "de", "fr", "cn", "ru", "br", "in", "ca", "jp", "kr", "au", "es", "it"]
        for country in countries:
            ProxyFetcherMega.PROXY_URLS.append(
                f"https://api.proxyscrape.com/v2/?request=get&protocol=http&country={country}&ssl=all&anonymity=all"
            )

    @staticmethod
    def _add_protocol_specific_sources():
        """Add protocol-specific sources"""
        protocols = ["http", "https", "socks4", "socks5"]
        for proto in protocols:
            ProxyFetcherMega.PROXY_URLS.extend([
                f"https://api.proxyscrape.com/v2/?request=get&protocol={proto}&ssl=all&anonymity=all",
                f"https://api.proxyscrape.com/v2/?request=get&protocol={proto}&ssl=yes&anonymity=elite",
                f"https://api.proxyscrape.com/v2/?request=get&protocol={proto}&ssl=no&anonymity=anonymous",
            ])

    @classmethod
    def getAllProxies(cls):
        """Get all proxies from all sources"""
        urls = cls.init_sources()
        print(f"Total sources: {len(urls)}")

        all_proxies = set()

        for i, url in enumerate(urls):
            try:
                resp = requests.get(url, timeout=10, verify=False)

                # Handle JSON API responses
                if "api." in url:
                    try:
                        data = resp.json()
                        if isinstance(data, dict):
                            if "data" in data and "proxies" in data["data"]:
                                for proxy in data["data"]["proxies"]:
                                    all_proxies.add(proxy)
                            elif "proxies" in data:
                                for proxy in data["proxies"]:
                                    all_proxies.add(proxy)
                        continue
                    except:
                        pass

                # Handle text responses
                for line in resp.text.strip().split('\n'):
                    line = line.strip()
                    if line and ':' in line and not line.startswith('#'):
                        all_proxies.add(line)

                if (i + 1) % 100 == 0:
                    print(f"Processed {i + 1}/{len(urls)} sources, {len(all_proxies)} proxies so far")

            except Exception as e:
                pass

        return list(all_proxies)

    @classmethod
    def getSourceCount(cls):
        """Get total number of sources"""
        return len(cls.init_sources())


if __name__ == "__main__":
    print(f"Total proxy sources available: {ProxyFetcherMega.getSourceCount()}")
